AllowUsers root dev
PermitRootLogin forced-commands-only
PasswordAuthentication no
KbdInteractiveAuthentication no
PubkeyAuthentication yes
SetEnv PATH=/opt/cmake/bin:/opt/rust/cargo/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin CUDA_HOME=/usr/local/cuda CUDA_VERSION=12.8.2 RUSTUP_HOME=/opt/rust/rustup CARGO_HOME=/workspace/.cache/cargo CARGO_TARGET_DIR=/workspace/dev/target CMAKE_GENERATOR=Ninja CMAKE_C_COMPILER_LAUNCHER=ccache CMAKE_CXX_COMPILER_LAUNCHER=ccache CMAKE_CUDA_COMPILER_LAUNCHER=ccache CCACHE_COMPILERCHECK=content CCACHE_DIR=/workspace/.cache/ccache CUDA_CACHE_PATH=/workspace/.cache/cuda RUSTC_WRAPPER=/usr/local/bin/sccache SCCACHE_DIR=/workspace/.cache/sccache STWO_GPU_DEV_IMAGE_VERSION=2026-07-16.2
PermitUserEnvironment LD_LIBRARY_PATH,LIBRARY_PATH,RUNPOD_POD_ID,RUNPOD_VOLUME_ID,RUNPOD_DC_ID,RUNPOD_GPU_COUNT
